### ISSUE TITLE
Sprint 1: TODO

### ISSUE THREAD

**Issue by bboe** [scalableinternetservices/NoteIt#2]
Please add to your "current" section on pivotal what it is you hope to accomplish in the first sprint. Please keep in mind that on Thursday you should have some feature(s) to demo to me so try to focus on providing some initial set of value to your customers (me).

**Comment by otownsend92** [comment]
Pivotal has been updated with new project stories. Current section has been updated to reflect Sprint 1 goals

**Comment by bboe** [comment]
Great! I provided a separate comment on Piazza. Feel free to ignore those suggestions if you're already underway with those stories.
