### ISSUE TITLE
Improve Project Description

### ISSUE THREAD

**Issue by bboe** [scalableinternetservices/NoteIt#3]
Can you please add more detail to the project description to include more detail on what it is users can do and/or how they might do it? Thanks!

**Comment by aviral26** [comment]
I have added a bit more to the README.

**Comment by bboe** [comment]
I'm not seeing it on the README:

> The aim for this project is to create a system where classmates can share notes for their classes

Could it have been overwritten, or maybe not pushed?

**Comment by otownsend92** [comment]
I'm not seeing it either. I checked through all the branches too just in case.

**Comment by otownsend92** [comment]
Updated it. Should I go into more detail on anything?

**Comment by bboe** [comment]
That's more than plenty of detail. Thanks!
